# Generated by Django 4.2.30 on 2026-07-22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.DateTimeField(db_index=True)),
                ("node_id", models.CharField(db_index=True, max_length=50)),
                ("metric_name", models.CharField(db_index=True, max_length=50)),
                ("value", models.FloatField()),
            ],
            options={"db_table": "telemetry", "managed": False},
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("location_lat", models.FloatField()),
                ("location_lon", models.FloatField()),
                ("status", models.CharField(default="online", max_length=20)),
                ("node_type", models.CharField(default="air_quality", max_length=50)),
                ("metadata_json", models.JSONField(blank=True, db_column="metadata_json", null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"db_table": "nodes"},
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("metric_name", models.CharField(db_index=True, max_length=50)),
                ("condition", models.CharField(max_length=10)),
                ("threshold", models.FloatField()),
                ("severity", models.CharField(default="warning", max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("node", models.ForeignKey(blank=True, db_column="node_id", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="alert_rules", to="greenpulse_app.node")),
            ],
            options={"db_table": "alert_rules"},
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("node_id", models.CharField(db_index=True, max_length=50)),
                ("metric_name", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("threshold", models.FloatField()),
                ("severity", models.CharField(max_length=20)),
                ("message", models.CharField(max_length=255)),
                ("triggered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("rule", models.ForeignKey(db_column="rule_id", on_delete=django.db.models.deletion.CASCADE, related_name="alerts", to="greenpulse_app.alertrule")),
            ],
            options={"db_table": "alerts"},
        ),
    ]
